//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.4
//     from Assets/Resources/Config/Input/GameInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Resources/Config/Input/GameInput.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @GameInput: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @GameInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""GameInput"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""87708b3a-a7b5-4413-ae59-de5d9387044a"",
            ""actions"": [
                {
                    ""name"": ""move"",
                    ""type"": ""Value"",
                    ""id"": ""6ac6cc39-cf4f-4449-80fe-fdbda54b5685"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""fastmove"",
                    ""type"": ""Button"",
                    ""id"": ""03772a76-6640-417e-af2e-2cd577679732"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""esc"",
                    ""type"": ""Button"",
                    ""id"": ""b1c2d3e4-1111-4000-8000-000000000001"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""togglebuildmenu"",
                    ""type"": ""Button"",
                    ""id"": ""b1c2d3e4-3333-4000-8000-000000000001"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""leftClick"",
                    ""type"": ""Button"",
                    ""id"": ""b1c2d3e4-5555-4000-8000-000000000001"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""leftClickRelease"",
                    ""type"": ""Button"",
                    ""id"": ""b1c2d3e4-9200-4000-8000-000000000001"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""rightClick"",
                    ""type"": ""Button"",
                    ""id"": ""b1c2d3e4-6666-4000-8000-000000000001"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""middleDrag"",
                    ""type"": ""Button"",
                    ""id"": ""b1c2d3e4-7777-4000-8000-000000000001"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""scroll"",
                    ""type"": ""Value"",
                    ""id"": ""b1c2d3e4-8888-4000-8000-000000000001"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""digit1"",
                    ""type"": ""Button"",
                    ""id"": ""b1c2d3e4-9001-4000-8000-000000000001"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""digit2"",
                    ""type"": ""Button"",
                    ""id"": ""b1c2d3e4-9002-4000-8000-000000000001"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""digit3"",
                    ""type"": ""Button"",
                    ""id"": ""b1c2d3e4-9003-4000-8000-000000000001"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""digit4"",
                    ""type"": ""Button"",
                    ""id"": ""b1c2d3e4-9004-4000-8000-000000000001"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""digit5"",
                    ""type"": ""Button"",
                    ""id"": ""b1c2d3e4-9005-4000-8000-000000000001"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""digit6"",
                    ""type"": ""Button"",
                    ""id"": ""b1c2d3e4-9006-4000-8000-000000000001"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""digit7"",
                    ""type"": ""Button"",
                    ""id"": ""b1c2d3e4-9007-4000-8000-000000000001"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""digit8"",
                    ""type"": ""Button"",
                    ""id"": ""b1c2d3e4-9008-4000-8000-000000000001"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""digit9"",
                    ""type"": ""Button"",
                    ""id"": ""b1c2d3e4-9009-4000-8000-000000000001"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""toggleTrainingMenu"",
                    ""type"": ""Button"",
                    ""id"": ""b1c2d3e4-9100-4000-8000-000000000001"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""a1b2c3d4-0001-4000-8000-000000000001"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""a1b2c3d4-0002-4000-8000-000000000002"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""a1b2c3d4-0003-4000-8000-000000000003"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""2a18a420-3b5a-4ccd-a8ae-ac4ed42fcb0b"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fastmove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6b904e01-5ec5-4629-9823-7cf253e79510"",
                    ""path"": ""<Keyboard>/rightShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fastmove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1c2d3e4-2222-4000-8000-000000000002"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""esc"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1c2d3e4-4444-4000-8000-000000000002"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""togglebuildmenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1c2d3e4-5555-4000-8000-000000000002"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""leftClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1c2d3e4-9200-4000-8000-000000000002"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""leftClickRelease"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1c2d3e4-6666-4000-8000-000000000002"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""rightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1c2d3e4-7777-4000-8000-000000000002"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""middleDrag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1c2d3e4-8888-4000-8000-000000000002"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""scroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1c2d3e4-9001-4000-8000-000000000002"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""digit1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1c2d3e4-9002-4000-8000-000000000002"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""digit2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1c2d3e4-9003-4000-8000-000000000002"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""digit3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1c2d3e4-9004-4000-8000-000000000002"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""digit4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1c2d3e4-9005-4000-8000-000000000002"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""digit5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1c2d3e4-9006-4000-8000-000000000002"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""digit6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1c2d3e4-9007-4000-8000-000000000002"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""digit7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1c2d3e4-9008-4000-8000-000000000002"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""digit8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1c2d3e4-9009-4000-8000-000000000002"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""digit9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1c2d3e4-9100-4000-8000-000000000002"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""toggleTrainingMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_move = m_Player.FindAction("move", throwIfNotFound: true);
        m_Player_fastmove = m_Player.FindAction("fastmove", throwIfNotFound: true);
        m_Player_esc = m_Player.FindAction("esc", throwIfNotFound: true);
        m_Player_togglebuildmenu = m_Player.FindAction("togglebuildmenu", throwIfNotFound: true);
        m_Player_leftClick = m_Player.FindAction("leftClick", throwIfNotFound: true);
        m_Player_leftClickRelease = m_Player.FindAction("leftClickRelease", throwIfNotFound: true);
        m_Player_rightClick = m_Player.FindAction("rightClick", throwIfNotFound: true);
        m_Player_middleDrag = m_Player.FindAction("middleDrag", throwIfNotFound: true);
        m_Player_scroll = m_Player.FindAction("scroll", throwIfNotFound: true);
        m_Player_digit1 = m_Player.FindAction("digit1", throwIfNotFound: true);
        m_Player_digit2 = m_Player.FindAction("digit2", throwIfNotFound: true);
        m_Player_digit3 = m_Player.FindAction("digit3", throwIfNotFound: true);
        m_Player_digit4 = m_Player.FindAction("digit4", throwIfNotFound: true);
        m_Player_digit5 = m_Player.FindAction("digit5", throwIfNotFound: true);
        m_Player_digit6 = m_Player.FindAction("digit6", throwIfNotFound: true);
        m_Player_digit7 = m_Player.FindAction("digit7", throwIfNotFound: true);
        m_Player_digit8 = m_Player.FindAction("digit8", throwIfNotFound: true);
        m_Player_digit9 = m_Player.FindAction("digit9", throwIfNotFound: true);
        m_Player_toggleTrainingMenu = m_Player.FindAction("toggleTrainingMenu", throwIfNotFound: true);
    }

    ~@GameInput()
    {
        UnityEngine.Debug.Assert(!m_Player.enabled, "This will cause a leak and performance issues, GameInput.Player.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_move;
    private readonly InputAction m_Player_fastmove;
    private readonly InputAction m_Player_esc;
    private readonly InputAction m_Player_togglebuildmenu;
    private readonly InputAction m_Player_leftClick;
    private readonly InputAction m_Player_leftClickRelease;
    private readonly InputAction m_Player_rightClick;
    private readonly InputAction m_Player_middleDrag;
    private readonly InputAction m_Player_scroll;
    private readonly InputAction m_Player_digit1;
    private readonly InputAction m_Player_digit2;
    private readonly InputAction m_Player_digit3;
    private readonly InputAction m_Player_digit4;
    private readonly InputAction m_Player_digit5;
    private readonly InputAction m_Player_digit6;
    private readonly InputAction m_Player_digit7;
    private readonly InputAction m_Player_digit8;
    private readonly InputAction m_Player_digit9;
    private readonly InputAction m_Player_toggleTrainingMenu;
    /// <summary>
    /// Provides access to input actions defined in input action map "Player".
    /// </summary>
    public struct PlayerActions
    {
        private @GameInput m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayerActions(@GameInput wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Player/move".
        /// </summary>
        public InputAction @move => m_Wrapper.m_Player_move;
        /// <summary>
        /// Provides access to the underlying input action "Player/fastmove".
        /// </summary>
        public InputAction @fastmove => m_Wrapper.m_Player_fastmove;
        /// <summary>
        /// Provides access to the underlying input action "Player/esc".
        /// </summary>
        public InputAction @esc => m_Wrapper.m_Player_esc;
        /// <summary>
        /// Provides access to the underlying input action "Player/togglebuildmenu".
        /// </summary>
        public InputAction @togglebuildmenu => m_Wrapper.m_Player_togglebuildmenu;
        /// <summary>
        /// Provides access to the underlying input action "Player/leftClick".
        /// </summary>
        public InputAction @leftClick => m_Wrapper.m_Player_leftClick;
        /// <summary>
        /// Provides access to the underlying input action "Player/leftClickRelease".
        /// </summary>
        public InputAction @leftClickRelease => m_Wrapper.m_Player_leftClickRelease;
        /// <summary>
        /// Provides access to the underlying input action "Player/rightClick".
        /// </summary>
        public InputAction @rightClick => m_Wrapper.m_Player_rightClick;
        /// <summary>
        /// Provides access to the underlying input action "Player/middleDrag".
        /// </summary>
        public InputAction @middleDrag => m_Wrapper.m_Player_middleDrag;
        /// <summary>
        /// Provides access to the underlying input action "Player/scroll".
        /// </summary>
        public InputAction @scroll => m_Wrapper.m_Player_scroll;
        /// <summary>
        /// Provides access to the underlying input action "Player/digit1".
        /// </summary>
        public InputAction @digit1 => m_Wrapper.m_Player_digit1;
        /// <summary>
        /// Provides access to the underlying input action "Player/digit2".
        /// </summary>
        public InputAction @digit2 => m_Wrapper.m_Player_digit2;
        /// <summary>
        /// Provides access to the underlying input action "Player/digit3".
        /// </summary>
        public InputAction @digit3 => m_Wrapper.m_Player_digit3;
        /// <summary>
        /// Provides access to the underlying input action "Player/digit4".
        /// </summary>
        public InputAction @digit4 => m_Wrapper.m_Player_digit4;
        /// <summary>
        /// Provides access to the underlying input action "Player/digit5".
        /// </summary>
        public InputAction @digit5 => m_Wrapper.m_Player_digit5;
        /// <summary>
        /// Provides access to the underlying input action "Player/digit6".
        /// </summary>
        public InputAction @digit6 => m_Wrapper.m_Player_digit6;
        /// <summary>
        /// Provides access to the underlying input action "Player/digit7".
        /// </summary>
        public InputAction @digit7 => m_Wrapper.m_Player_digit7;
        /// <summary>
        /// Provides access to the underlying input action "Player/digit8".
        /// </summary>
        public InputAction @digit8 => m_Wrapper.m_Player_digit8;
        /// <summary>
        /// Provides access to the underlying input action "Player/digit9".
        /// </summary>
        public InputAction @digit9 => m_Wrapper.m_Player_digit9;
        /// <summary>
        /// Provides access to the underlying input action "Player/toggleTrainingMenu".
        /// </summary>
        public InputAction @toggleTrainingMenu => m_Wrapper.m_Player_toggleTrainingMenu;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayerActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayerActions" />
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @move.started += instance.OnMove;
            @move.performed += instance.OnMove;
            @move.canceled += instance.OnMove;
            @fastmove.started += instance.OnFastmove;
            @fastmove.performed += instance.OnFastmove;
            @fastmove.canceled += instance.OnFastmove;
            @esc.started += instance.OnEsc;
            @esc.performed += instance.OnEsc;
            @esc.canceled += instance.OnEsc;
            @togglebuildmenu.started += instance.OnTogglebuildmenu;
            @togglebuildmenu.performed += instance.OnTogglebuildmenu;
            @togglebuildmenu.canceled += instance.OnTogglebuildmenu;
            @leftClick.started += instance.OnLeftClick;
            @leftClick.performed += instance.OnLeftClick;
            @leftClick.canceled += instance.OnLeftClick;
            @leftClickRelease.started += instance.OnLeftClickRelease;
            @leftClickRelease.performed += instance.OnLeftClickRelease;
            @leftClickRelease.canceled += instance.OnLeftClickRelease;
            @rightClick.started += instance.OnRightClick;
            @rightClick.performed += instance.OnRightClick;
            @rightClick.canceled += instance.OnRightClick;
            @middleDrag.started += instance.OnMiddleDrag;
            @middleDrag.performed += instance.OnMiddleDrag;
            @middleDrag.canceled += instance.OnMiddleDrag;
            @scroll.started += instance.OnScroll;
            @scroll.performed += instance.OnScroll;
            @scroll.canceled += instance.OnScroll;
            @digit1.started += instance.OnDigit1;
            @digit1.performed += instance.OnDigit1;
            @digit1.canceled += instance.OnDigit1;
            @digit2.started += instance.OnDigit2;
            @digit2.performed += instance.OnDigit2;
            @digit2.canceled += instance.OnDigit2;
            @digit3.started += instance.OnDigit3;
            @digit3.performed += instance.OnDigit3;
            @digit3.canceled += instance.OnDigit3;
            @digit4.started += instance.OnDigit4;
            @digit4.performed += instance.OnDigit4;
            @digit4.canceled += instance.OnDigit4;
            @digit5.started += instance.OnDigit5;
            @digit5.performed += instance.OnDigit5;
            @digit5.canceled += instance.OnDigit5;
            @digit6.started += instance.OnDigit6;
            @digit6.performed += instance.OnDigit6;
            @digit6.canceled += instance.OnDigit6;
            @digit7.started += instance.OnDigit7;
            @digit7.performed += instance.OnDigit7;
            @digit7.canceled += instance.OnDigit7;
            @digit8.started += instance.OnDigit8;
            @digit8.performed += instance.OnDigit8;
            @digit8.canceled += instance.OnDigit8;
            @digit9.started += instance.OnDigit9;
            @digit9.performed += instance.OnDigit9;
            @digit9.canceled += instance.OnDigit9;
            @toggleTrainingMenu.started += instance.OnToggleTrainingMenu;
            @toggleTrainingMenu.performed += instance.OnToggleTrainingMenu;
            @toggleTrainingMenu.canceled += instance.OnToggleTrainingMenu;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayerActions" />
        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @move.started -= instance.OnMove;
            @move.performed -= instance.OnMove;
            @move.canceled -= instance.OnMove;
            @fastmove.started -= instance.OnFastmove;
            @fastmove.performed -= instance.OnFastmove;
            @fastmove.canceled -= instance.OnFastmove;
            @esc.started -= instance.OnEsc;
            @esc.performed -= instance.OnEsc;
            @esc.canceled -= instance.OnEsc;
            @togglebuildmenu.started -= instance.OnTogglebuildmenu;
            @togglebuildmenu.performed -= instance.OnTogglebuildmenu;
            @togglebuildmenu.canceled -= instance.OnTogglebuildmenu;
            @leftClick.started -= instance.OnLeftClick;
            @leftClick.performed -= instance.OnLeftClick;
            @leftClick.canceled -= instance.OnLeftClick;
            @leftClickRelease.started -= instance.OnLeftClickRelease;
            @leftClickRelease.performed -= instance.OnLeftClickRelease;
            @leftClickRelease.canceled -= instance.OnLeftClickRelease;
            @rightClick.started -= instance.OnRightClick;
            @rightClick.performed -= instance.OnRightClick;
            @rightClick.canceled -= instance.OnRightClick;
            @middleDrag.started -= instance.OnMiddleDrag;
            @middleDrag.performed -= instance.OnMiddleDrag;
            @middleDrag.canceled -= instance.OnMiddleDrag;
            @scroll.started -= instance.OnScroll;
            @scroll.performed -= instance.OnScroll;
            @scroll.canceled -= instance.OnScroll;
            @digit1.started -= instance.OnDigit1;
            @digit1.performed -= instance.OnDigit1;
            @digit1.canceled -= instance.OnDigit1;
            @digit2.started -= instance.OnDigit2;
            @digit2.performed -= instance.OnDigit2;
            @digit2.canceled -= instance.OnDigit2;
            @digit3.started -= instance.OnDigit3;
            @digit3.performed -= instance.OnDigit3;
            @digit3.canceled -= instance.OnDigit3;
            @digit4.started -= instance.OnDigit4;
            @digit4.performed -= instance.OnDigit4;
            @digit4.canceled -= instance.OnDigit4;
            @digit5.started -= instance.OnDigit5;
            @digit5.performed -= instance.OnDigit5;
            @digit5.canceled -= instance.OnDigit5;
            @digit6.started -= instance.OnDigit6;
            @digit6.performed -= instance.OnDigit6;
            @digit6.canceled -= instance.OnDigit6;
            @digit7.started -= instance.OnDigit7;
            @digit7.performed -= instance.OnDigit7;
            @digit7.canceled -= instance.OnDigit7;
            @digit8.started -= instance.OnDigit8;
            @digit8.performed -= instance.OnDigit8;
            @digit8.canceled -= instance.OnDigit8;
            @digit9.started -= instance.OnDigit9;
            @digit9.performed -= instance.OnDigit9;
            @digit9.canceled -= instance.OnDigit9;
            @toggleTrainingMenu.started -= instance.OnToggleTrainingMenu;
            @toggleTrainingMenu.performed -= instance.OnToggleTrainingMenu;
            @toggleTrainingMenu.canceled -= instance.OnToggleTrainingMenu;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerActions.UnregisterCallbacks(IPlayerActions)" />.
        /// </summary>
        /// <seealso cref="PlayerActions.UnregisterCallbacks(IPlayerActions)" />
        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayerActions.AddCallbacks(IPlayerActions)" />
        /// <seealso cref="PlayerActions.RemoveCallbacks(IPlayerActions)" />
        /// <seealso cref="PlayerActions.UnregisterCallbacks(IPlayerActions)" />
        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayerActions" /> instance referencing this action map.
    /// </summary>
    public PlayerActions @Player => new PlayerActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Player" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayerActions.AddCallbacks(IPlayerActions)" />
    /// <seealso cref="PlayerActions.RemoveCallbacks(IPlayerActions)" />
    public interface IPlayerActions
    {
        /// <summary>
        /// Method invoked when associated input action "move" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "fastmove" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFastmove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "esc" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnEsc(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "togglebuildmenu" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTogglebuildmenu(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "leftClick" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftClick(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "leftClickRelease" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftClickRelease(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "rightClick" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightClick(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "middleDrag" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMiddleDrag(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "scroll" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnScroll(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "digit1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDigit1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "digit2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDigit2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "digit3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDigit3(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "digit4" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDigit4(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "digit5" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDigit5(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "digit6" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDigit6(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "digit7" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDigit7(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "digit8" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDigit8(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "digit9" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDigit9(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "toggleTrainingMenu" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnToggleTrainingMenu(InputAction.CallbackContext context);
    }
}
